CC = i686-elf-gcc
AS = i686-elf-as
LD = i686-elf-ld

CFLAGS  = -ffreestanding -O2 -Wall -Wextra -m32
LDFLAGS = -T linker.ld -nostdlib

OBJS = boot.o kernel.o

all: kernel.elf run

boot.o: boot.S
	$(AS) -32 $< -o $@

kernel.o: kernel.c
	$(CC) $(CFLAGS) -c $< -o $@

kernel.elf: $(OBJS) linker.ld
	$(LD) $(LDFLAGS) -o $@ $(OBJS)

run: kernel.elf
	qemu-system-i386 -kernel kernel.elf

clean:
	rm -f $(OBJS) kernel.elf

